### ISSUE TITLE
Request detail: Action buttons

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#108]
The following buttons should be added to the request details page.
- [ ] Cancel button. It should allow the creator of the request to cancel it's request (so it should be available for the user that created the requests).
- [ ] Decline button. It should allow the receiver of the request to reject it, opening a modal to indicate in a comment why the request was declined.
- [ ] Accept/publish button. It should vary between "accept" or "accept and publish", the second one should appear if a record was published on accept, while the first, in the rest of cases-

Each of the buttons should, upon interaction, call to the associated command of the relevant request.

**Comment by jrcastro2** [comment]
closed by https://github.com/inveniosoftware/invenio-requests/pull/126
