### ISSUE TITLE
Request detail: preview record tab

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#111]

**Comment by jrcastro2** [comment]
Current preview landing page is a jinja template ([here the code](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/records_ui/views/records.py#L69-L93)). In consequence (as far as I understand) it's not possible to have the record tab previewing the record unless we have 2 different views for the preview, one with jinja and another with react, I personally would discard this as it's hard to mantain and only adds complexity. In my opinion I see 2 different solutions:

1.  The preview view is not inside the record tab but it's just a button that will redirect to the already implemented preview view, as it's done currently in the deposit form, this way we can reuse the jinja template.
 **Cons:** We change [the initial design](https://codimd.web.cern.ch/ICyKqzFLQgi3PXAnMcMxlA#Request-detail) by removing the "record" tab and adding the preview button and it's less user-friendly. 
**Pros:** easy to implement, easy to maintain.

2. Re-implement the preview page in react, this way we can have different views reusing the same components. 
**Cons:** Redesign the landing page with react, doesn't make much sense to have a "static" page that doens't need any state build with react.
 **Pros:** Easy to reuse components in differents preview views. 

I would personally go with the first one.

**Comment by kprzerwa** [comment]
2 more possibilities:
3. implement tabs in jinja and include the details.html template (not sure how big would the implications be, especially if we are talking about differences in serializers, its potentially complicated)
4. iframe to the records detail view
