### ISSUE TITLE
requests ui: commenting permissions

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#156]
Currently we display the edit/delete actions for each comment, however the user should not be able to perform any actions on a comment which was not written originally by the user.
The actions should not be visible if the user has no permissions to perform edit/delete of a specific comment. 

Solution 1:
A user should only be available to edit or delete a request (in this case a comment) it it has the permissions required for those actions, which, as defined in the configuration https://github.com/inveniosoftware/invenio-requests/blob/2f3a281c7f9718d0df30bae9db4a84a94b6c926d/invenio_requests/services/permissions.py#L81-L88, require, in both cases, that the request was created by the user.

Getting this permissions in the _frontend_ can be, as far as I have tested, a bit problematic, and, in my opinion, the best solution would be to create  and API endpoint to obtain the permissions given an object and a record. This solution has been discussed and may be quite overkill and complex for such a small feature. 

Solution 2:
A way simpler and even cleaner solution would be to compare the created_by field of the comment with the id of the logged user, showing the edit/delete dropdown if both match.

To discuss:
- should a community manager/admin be able to edit or delete someone's comment?

**Comment by ntarocco** [comment]
As discussed, investigate a 3rd solution to expose the permissions of the current logged in user for each event, as done for the members.
