### ISSUE TITLE
Requests details: comment is shown twice

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-requests#185]
1. Create a new draft
2. Submit to a community with a comment

![Screenshot 2022-04-19 at 12 16 44](https://user-images.githubusercontent.com/2089455/163982829-a7cea3fd-9f6b-4877-9e42-ec23b34f4717.png)

**Comment by NRodriguezcuellar** [comment]
is caused by the mock data pushing the first event to the end of the timeline, should be closed with https://github.com/inveniosoftware/invenio-requests/issues/183

**Comment by zzacharo** [comment]
Fixed https://github.com/inveniosoftware/invenio-requests/pull/198
