### ISSUE TITLE
request details: username not resolved in the payload

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#191]
resources affected:
request
request timeline
<img width="850" alt="Screenshot 2022-04-25 at 10 46 17" src="https://user-images.githubusercontent.com/38131488/165053964-f7e47598-8c85-4556-be44-13f8d00c771d.png">
<img width="1113" alt="Screenshot 2022-04-25 at 10 46 27" src="https://user-images.githubusercontent.com/38131488/165053969-b2607479-79c4-49b1-a9db-418eac34c1c0.png">

after providing the username in the payload, frontend needs to be updated to include the username
<img width="1673" alt="Screenshot 2022-04-25 at 10 10 10" src="https://user-images.githubusercontent.com/38131488/165054167-6488372c-5dd9-4737-b9c9-54a40f5a783b.png">

**Comment by jrcastro2** [comment]
Checked in version [v0.3.25](https://github.com/inveniosoftware/invenio-requests/commit/b20dd62ad29c2dd0a6d2f2e199378f75171b14cd) and is fixed, expanded field contains the username and frontend displays it correctly.

![image](https://user-images.githubusercontent.com/15194802/171374899-b69d8d46-6447-48b3-a530-b42d8d01f27a.png)
