### ISSUE TITLE
community requests search: creator of the request incorrect

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#196]
Package version (if known): <version>

## Describe the bug
" opened 7 minutes by you"  - `you` does not represent the actual creator of the request, it should point to a specific username, unless the creator is indeed the current user

## Screenshots (if applicable)
![Screenshot 2022-04-26 at 15 23 43](https://user-images.githubusercontent.com/38131488/165310028-8cc31195-46a8-42b8-936e-060812e07598.png)

**Comment by jrcastro2** [comment]
User and community are still not resolved. 
![image](https://user-images.githubusercontent.com/15194802/166211676-92c4a288-2cec-424b-a176-527a587cd875.png)
