### ISSUE TITLE
Fix UI bugs in request details page

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-requests#204]
Package version (if known): v9.0.0.dev14

## Describe the bug
Fix the various bugs in the UI for requests details page

## Steps to Reproduce
1. Go to details page of any request
2. See long text being cut
3. Try to edit a comment and see the overflow
4. Actions are missing the first capital letter
5. The cancel modal contains the word cancel twice. Maybe a solution could be to use "Cancel" and "Confirm" for all the actions.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/166672998-e5a42893-d55a-4adf-9599-37fc098b7bc6.png)

![image](https://user-images.githubusercontent.com/15194802/166673010-c44a09cb-79b1-416d-a15a-333d377cb65e.png)

**Comment by kpsherva** [comment]
the second screenshot probably needs also request actions translations to be implemented, I would suggest opening a separate issue for that?

**Comment by jrcastro2** [comment]
still issue on comments 
![image](https://user-images.githubusercontent.com/15194802/169524260-cc439fc0-56d5-40a7-af8c-384440d64d30.png)
