### ISSUE TITLE
request details: created field is not refreshing

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-requests#224]
<img width="395" alt="Screenshot 2022-05-18 at 16 34 46" src="https://user-images.githubusercontent.com/38131488/169067749-8983f561-438c-444e-a868-ea25cf83101b.png">

The request timeline is refreshing the relative time, but not the created field on the right panel, which makes it look strange

**Comment by jrcastro2** [comment]
Agreed to keep it as it is.
