### ISSUE TITLE
Implement feedback on mobile user requests.

### ISSUE THREAD

**Issue by Pineirin** [inveniosoftware/invenio-requests#264]
According to the feedback received, the following changes should be implemented on the mobile view of user requests:

- Center all content, of each of the requests.
- Move all the action buttons to a drop-down, the buttons should be hidden until the drop-down is opened. The proposed default drop-down is a vertical ellipsis.

**Comment by kpsherva** [comment]
The components implemented are too complex in terms of overriding, there is a simpler way by using Media component from
https://www.npmjs.com/package/@artsy/fresnel?activeTab=readme, which should be implemented only in the RequestActions (invenio-requests module) without a need to provide overriden component. 
In addition we decided with @jennur to replace the buttons in the dropdown by simpler menu options (standard dropdown), therefore it should be aligned
