### ISSUE TITLE
Get rid of `can_execute` (?)

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-requests#91]
Since Permission generators are checking for the state of the request (https://github.com/inveniosoftware/invenio-requests/pull/89/files#diff-c99cd4daf8be735b07bb8e24ff8f5d3121ce35f27ab2e297c964c9a27a7d0639R19) now, does it still make sense to keep `can_execute` checks in `RequestAction`s? 

I think not because it muddies the water as to where the rule for whether an action can be execute or not is placed: we don't know if it's one or the other or both... 

The alternative is keep that state check separate from the Permission generators and in `can_execute`. The permission generators would not do checks against request state.

**Comment by max-moser** [comment]
as discussed with @lnielsen earlier, we probably want to keep both around:
the permission generators would likely do the light-weight permission checks (and search filtering), while `can_execute` would potentially do some heavy lifting (such as validating the record draft before allowing execution of the `accept` action on community submission requests)

**Comment by fenekku** [comment]
closing for now until this resurfaces
